account/urls.py
from django.urls import path

from . import views
app_name='account'
urlpatterns = [
    path('accounts/login/', views.user_login, name='login'),
    path('accounts/logout/', views.user_logout, name='logout'),
]

main/urls.py
from django.urls import path

from . import views

app_name='main'

urlpatterns = [
    path('', views.choose_room, name='choose-room'),

    # 游戏主页面
    path('index', views.index, name='index'),

    # 游戏子页面
    path('game/get_state/', views.get_cur_state, name='get_state'),
    path('game/init/', views.init, name='init'),
    path('game/auth/', views.authenticate, name='auth'),
    path('game/commander/', views.choose_cmd, name='commander'),
    path('game/house/', views.open_house, name='open_house'),
    path('game/gameover/', views.game_over, name='game_over'),
    path('game/<slug:name>/', views.game, name='game'),

    # 进入房间页面
    path('room', views.room, name='room'),

    # 数据库初始化
    path('db_init', views.db_init, name='db_init'),

    # 进入房间页面
    path('choose_rank', views.choose_rank, name='choose_rank'),

    # 跳伞接口
    path('parachute', views.parachute, name='parachute'),

]

pubgsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('account.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Box(models.Model):
    password = models.IntegerField(default=None, null=True)
    position_x = models.IntegerField(default=None, null=True)
    position_y = models.IntegerField(default=None, null=True)
    size = models.IntegerField(default=None, null=True)
    least_num = models.IntegerField(default=None, null=True)


class Room(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=255)


class Users(models.Model):
    def __str__(self):
        return self.user.username

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_name = models.CharField(default="", null=True, max_length=255)
    rank = models.IntegerField(default=-1, null=True)
    group_id = models.IntegerField(default=None)
    is_commander = models.BooleanField(default=None, null=True)
    position_x = models.IntegerField(default=None, null=True)
    position_y = models.IntegerField(default=None, null=True)
    public_key = models.TextField(default=None, null=True)
    private_key = models.TextField(default=None, null=True)
    rsa_n = models.TextField(default=None, null=True)
    mill_rand = models.TextField(default=None, null=True)
    mill_prime = models.TextField(default=None, null=True)
    vote_to = models.IntegerField(default=None, null=True)
    box_key_x = models.IntegerField(default=None, null=True)
    box_key_y = models.IntegerField(default=None, null=True)
    certificating_with = models.IntegerField(default=None, null=True)
    opening_box = models.IntegerField(default=None, null=True)

    room = models.ForeignKey(Room, on_delete=models.CASCADE)


class SystemParam(models.Model):
    def __str__(self):
        return self.key

    key = models.CharField(max_length=255)
    intValue = models.IntegerField(default=None, null=True)
    strValue = models.CharField(max_length=255, default=None, null=True)


class Rank(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=255)

main/views.py
#-*- coding:utf-8 -*-
import json,random
from django.shortcuts import render

import csv, bisect, json, logging, random
import rsa as yynrsa
from . import rsa_jz as rsa
from django.conf import settings
from django.contrib.auth.models import User, Group
# from django.core.files import File
# from django.core.files.storage import FileSystemStorage
from django.db.models import Q
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required

from django.http import HttpResponse, Http404

import json,random
from django.shortcuts import render
from django.contrib.auth.models import User

from . import models, prime, lagrange
from . import initialization

logger = logging.getLogger(__name__)
PAGE_SIZE = 10

GROUP_DICT = {'admin': '管理员', 'guest': '访客', 'user': '用户'}

# Create your views here.

from django.http import HttpResponse

# 接口
@login_required
def index(request):
    return render(request, 'main/index.html')


@login_required
def game(request, name='firstGame'):
    return render(request, f'main/game.html', {"game_path": f"main/js/{name}.js"})


@login_required
def db_init(request):
    models.Users.objects.update(is_commander=0, position_x=-1, position_y=-1,
                                public_key=None, private_key=None, mill_rand=None, mill_prime=None,
                                room_id=1, box_key_x=None, box_key_y=None, certificating_with=-1,
                                opening_box=-1, rsa_n=None, vote_to=-1, rank=1)
    global_state=models.SystemParam.objects.get(key='global_status')
    global_state.intValue=0
    global_state.save()
    commander=models.SystemParam.objects.get(key='commander')
    commander.strValue=''
    commander.save()
    candidates=models.SystemParam.objects.get(key='candidates')
    candidates.strValue=''
    candidates.save()
    print(global_state)

    models.Box.objects.update(password=None)
    for i in range(5):
        j=i+1
        models.Users.objects.filter(id=j).update(user_name=User.objects.get(id=j).username)

    return redirect('main:choose-room')


@login_required
def choose_room(request):
    userDtb = models.User.objects.raw("select a.id, a.name as room_name, group_concat(c.username) as user_name from main_room a left join main_users b on a.id = b.room_id left join auth_user c on c.id = b.user_id group by a.id")
    context = {}
    context['rooms'] = userDtb
    ranks = models.Rank.objects.raw("select id,name from main_rank")
    context['ranks'] = ranks
    sql = "select a.id,a.name from main_rank a left join main_users b on a.id = b.rank left join auth_user c on c.id = b.user_id where c.id = " + request.user.id.__str__()
    currentRank = models.Rank.objects.raw(sql)
    context['current'] = currentRank
    return render(request, 'main/room.html', context)


@login_required
def room(request):
    r = request.GET['r']
    user_id = request.user.id
    models.Users.objects.filter(user_id=user_id).update(room_id=r)
    return redirect('main:choose-room')

@login_required
def choose_rank(request):
    rank = int(request.GET['rank'])
    user_id = request.user.id
    if rank != -1:
        if rank < 1 or rank > 18:
            rank = random.randint(1, 18)
    models.Users.objects.filter(user_id=user_id).update(rank=rank)
    return redirect('main:choose-room')


@login_required
def parachute(request):
    return 1


@login_required
def move(request):
    return 1


@login_required
def certificate(request):
    return 1


@login_required
def choose_cmd(request):
    user_id = request.user.id
    user = models.Users.objects.get(id=user_id)
    all_users = models.Users.objects.filter(group_id=user.group_id)

    global_state=models.SystemParam.objects.get(key='global_status').intValue

    commander=models.SystemParam.objects.get(key='commander').strValue
    if commander:
        info = f'选取指挥官成功，指挥官是{commander}。'
        return_dict = {
                'success': 1,
                'need_vote': 0,
                'info': info,
                'candidates': [],
                'commander': commander
            }
        return HttpResponse(json.dumps(return_dict))

    if global_state==4:
        return_dict = {
                'success': 0,
                'need_vote': 0,
                'info': '正在选取指挥官...',
                'candidates':[],
                'commander': ''
            }
        return HttpResponse(json.dumps(return_dict))

    if global_state == 3:
        if request.POST['vote'] == '1':
            authName = request.POST['vote_commander']
            authVC = User.objects.get(username=authName)
            user.vote_to = authVC.id
            user.save()
        need_vote = 0
        candidates=[]
        info='正在投票选出指挥官中，请耐心等待。'
        okFlag = 1
        cs = []
        vote_id = []
        if user.vote_to<0:
            need_vote=1
            candidates=models.SystemParam.objects.get(key='candidates').strValue.split(',')
            info = f"{', '.join(candidates)}的军衔并列最高，需要投票选出指挥官。"
            okFlag = 0
        else:
            for u in all_users:
                if u.vote_to <0:
                    okFlag = 0
                    break
                else:
                    if u.vote_to not in vote_id:
                        vote_id.append(u.vote_to)
                        cs.append(models.Users.objects.get(id=u.vote_to))

        if okFlag == 0:
            return_dict = {
                'success': 0,
                'need_vote': need_vote,
                'info': info,
                'candidates':candidates ,
                'commander': ''
            }
        else:
            commander = voteLeader(cs,all_users)
            authCom = User.objects.get(id=commander.id)
            info = f'选取指挥官成功，指挥官是{authCom.username}。'

            commander=models.SystemParam.objects.get(key='commander')
            commander.strValue=authCom.username
            commander.save()

            return_dict = {
                'success': 1,
                'need_vote': 0,
                'info': info,
                'candidates': [authCom.username],
                'commander': authCom.username
            }
            initialization.change_system_status(4)
        return HttpResponse(json.dumps(return_dict))

    #print(all_users)
    (tempResult,commander,setP,setQ,setR) = findLeader(all_users)
    #print((tempResult,commander,setP,setQ,setR))
    if tempResult == 0:
        authCom = User.objects.get(id=commander.id)
        info = f'选取指挥官成功，指挥官是{authCom.username}。'

        commander=models.SystemParam.objects.get(key='commander')
        commander.strValue=authCom.username
        commander.save()

        return_dict = {
            'success': 1,
            'need_vote': 0,
            'info': info,
            'candidates': [authCom.username],
            'commander': authCom.username
        }
        initialization.change_system_status(4)
    else:
        can = []
        for u in setQ:
            tempAU = User.objects.get(id=u.id)
            can.append(tempAU.username)
        return_dict = {
            'success': 0,
            'need_vote': 1,
            'info': f"{', '.join(can)}的军衔并列最高，需要投票选出指挥官。",
            'candidates': can,
            'commander': ''
        }
        candidates = models.SystemParam.objects.get(key='candidates')
        candidates.strValue = ','.join(can)
        candidates.save()
        initialization.change_system_status(3)

    return HttpResponse(json.dumps(return_dict))



def init(request):
    '''
    :param player_id: the player_id is expected to be in [0, 4]
    :return:
    '''

    return HttpResponse(initialization.get_all_positions(request.user.id))

def get_cur_state(request):
    username = request.user.get_username()
    user_id = request.user.id
    user = models.Users.objects.get(user_id=user_id)

    user.position_x = request.POST['position_x']
    user.position_y = request.POST['position_y']
    user.save()

    user_list = models.Users.objects.all()
    global_status = models.SystemParam.objects.get(key='global_status')
    other_players = {}
    known_count = 0
    for u in user_list:
        same_group = 0
        if u.user_id == user_id:
            continue
        elif u.group_id == user.group_id:
            same_group = 1
            known_count += 1
        other_players[u.user.get_username()] = {'position': [u.position_x, u.position_y],
                                    'known': same_group}

    if (known_count >= 4) and (global_status.intValue == 1):
        global_status.intValue = 2
        global_status.save()

    can_choose_commander = 0
    if global_status.intValue >=2: #and (user.vote_to <= 0):
        can_choose_commander = 1

    return_dict = {
        'player': username,
        'position': [user.position_x, user.position_y],
        'can_choose_commander': can_choose_commander,
        'otherPlayers': other_players
    }

    if user.certificating_with > 0:
        print(f'auth:{user.certificating_with}')
        c_username = User.objects.get(id=user.certificating_with).get_username()
        return_dict['event'] = {'name': 'auth',
                                'username': c_username,
                                'info': '你正在和' + c_username + '认证。'}
    if user.opening_box > 0:
        return_dict['event'] = {'name': 'open_house',
                                'house_id': user.opening_box,
                                'info': '你正在开启' + str(user.opening_box) + '号房子。'}

    global_status = models.SystemParam.objects.get(key='global_status').intValue
    #TODO: fetch candidates list
    if global_status == 3:
        if user.vote_to <= 0:
            candidates = ['junzhou','hainan']
            return_dict['event'] = {'name': 'vote_commander',
                                    'info': '选举指挥官'}
            # 'candidates': candidates,
    elif global_status == 5:
        return_dict['event'] = {'name': 'game_over',

templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}数据查询{% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <link type="text/css" href="{% static "main/css/bootstrap.min.css"%}" rel="stylesheet">
    <link type="text/css" href="{% static "main/css/fontawesom-all.css" %}" rel="stylesheet">

    <script src="{% static "main/js/jquery-3.4.1.js" %}"></script>
    <script src="{% static "main/js/popper.min.js" %}"></script>
    <script src="{% static "main/js/bootstrap.min.js" %}"></script>

    <link type="text/css" rel="stylesheet" href="{% static "main/css/index.css" %}">

    {% block extra_head %}{% endblock %}

</head>
<body>
<nav class="navbar navbar-expand-md bkg-white-color border-bottom navbar-light px-3 py-0 fixed-top shadow">
    <!-- Brand -->
    <a class="navbar-brand" href="{% url 'main:index' %}">
        <h5 class="p-0 m-0">伞兵作战模拟系统</h5>
    </a>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link p-3 " href=""  data-toggle="dropdown">
                    <h5 class="p-0 m-0">数据库管理</h5>
                </a>
                <div class="dropdown-menu border-0 rounded-0 m-0 py-0 ">
                    <a class="dropdown-item px-3 py-2" href="{% url 'main:db_init' %}">
                        初始化数据库
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link p-3  " href="" data-toggle="dropdown">
                    <h5 class="p-0 m-0">{{ user.username }}</h5>
                </a>
                <div class="dropdown-menu border-0 rounded-0 m-0 py-0 ">
                    <!--<a class="dropdown-item px-3 py-2" href="/admin">
                        用户管理
                    </a>-->
                    <a class="dropdown-item px-3 py-2" href="{% url 'account:logout' %}">
                        登出
                    </a>
                </div>
            </li>

        </ul>
    </div>
</nav>

{% block content %}{% endblock %}

<footer class="container-fluid bkg-white-color border-top py-1 mt-2 fixed-bottom">
    <div class="row">
        <div class="col-sm-12 d-flex justify-content-between">
            <span>Copyright &copy; 2019 Cyber Security Group 4</span>
            <span>{% now "jS F Y H:i"  %}</span>
        </div>
    </div>
</footer>
</body>

templates/main/game.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <script src="{% static "main/js/jquery-3.4.1.js" %}"></script>
    <script src="{% static "main/js/phaser.js" %}"></script>
    <script src="{% static game_path %}"></script>
    <script type="text/javascript">
        window.CSRF_TOKEN = "{{ csrf_token }}";
        INIT_URL="{% url 'main:init' %}";
        STATE_URL="{% url 'main:get_state' %}";
        AUTH_URL="{% url 'main:auth' %}";
        COMMANDER_URL="{% url 'main:commander' %}";
        OPEN_HOUSE_URL="{% url 'main:open_house' %}";
        GAME_OVER_URL="{% url 'main:game_over' %}";
    </script>
</head>
</html>

templates/main/index.html
{% extends "./base.html" %}

{% block title %}伞兵作战模拟系统{% endblock %}

{% block extra_head %}
    {% load static %}
    <script src="{% static "main/js/phaser.js" %}"></script>
{% endblock %}

{% block content %}
    <div class="container-fluid px-5" style="margin-top:90px;margin-bottom: 30px">
        <div class="row my-2 mx-5" >
            <div class="col p-0 d-flex justify-content-center">
                <iframe class="border border-primary" src="{% url 'main:game' 'game' %}" style="width:1622px;height: 823px;" allowfullscreen></iframe>
                <!--<div class="embed-responsive embed-responsive-1by1">
                    <iframe class=" embed-responsive-item" src="{% url 'main:game' 'game' %}" allowfullscreen></iframe>
                </div>-->
            </div>
            <!--<div class="col-3">hello world</div>-->
        </div>
    </div>
{% endblock %}

templates/main/room.html
{% extends "./base.html" %}

{% block title %}选择房间{% endblock %}

{% block extra_head %}
    {% load static %}
    <link rel="stylesheet" href="{% static "main/css/style.css" %}" type="text/css" />
    <link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css">
{% endblock %}

{% block content %}
    <br><br><br>
<div class="bodyCon08"><!--学员-->
    <div style="float:right;">
        <a href="{% url 'main:index' %}">
        <button type="button" class="btn btn-info" id="parachuteButton" style="height: 480px;background-color:#666666">跳伞</button>
        </a>
    </div>
    <div class="students">

        <div id="four_flash">
            <div class="flashBg">
                <ul class="mobile">
                    <li>
                        <img src="{% static "main/images/senke_xy03.jpg" %}" />
                        <dd>房间一</dd>
                        <p>用于友军</p>
                        <a href="/room?r=1"></a>
                    </li>
                    <li>
                        <img src="{% static "main/images/senke_xy01.jpg" %}" />
                        <dd>房间二</dd>
                        <p>用于敌军</p>
                        <a href="/room?r=2"></a>
                    </li>
                    <li>
                        <img src="{% static "main/images/senke_xy04.jpg" %}" />
                        <dd>房间三</dd>
                        <p>凑数</p>
                        <a href="/room?r=3"></a>
                    </li>
                </ul>
            </div>
            <div class="but_left"><img src="{% static "main/images/qianxleft.png" %}" /></div>
            <div class="but_right"><img src="{% static "main/images/qianxr.png" %}" /></div>
        </div>
    </div>

</div>

<table class="table table-hover">
    {% for room in rooms %}
    <tr>
        <td width="200">
            {{room.room_name}}
        </td>
        <td>
            {{ room.user_name }}
        </td>
    </tr>
    {% endfor %}

</table>

<div class="container">
    <div class="card-drop">

        <a class='toggle' href="javascript:void(0)">
            <i class='fa fa-suitcase'></i>
              <span class='label-active'>您当前的军衔为：<strong>{% for cur in current %}{{ cur.name }}{% endfor %}</strong></span>
        </a>
        <ul>
            <li>
                <a data-label="{{ rank.name }}" href="/choose_rank?rank=-1"><i class='fa fa-suitcase'></i>&nbsp;</a>
            </li>
            <li>
                <a data-label="{{ rank.name }}" href="/choose_rank?rank=0"><i class='fa fa-suitcase'></i> 随机</a>
            </li>
            {% for rank in ranks %}
            <li>
                <a data-label="{{ rank.name }}" href="/choose_rank?rank={{ rank.id }}"><i class='fa fa-suitcase'></i> {{ rank.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>



<script type="text/javascript" src="{% static "main/js/jquery.min.js" %}"></script>
<script type="text/javascript">
//学员
var _index5=0;

$("#four_flash .but_right img").click(function(){
	_index5++;
	var len=$(".flashBg ul.mobile li").length;
	if(_index5+5>len){
		$("#four_flash .flashBg ul.mobile").stop().append($("ul.mobile").html());
	}
	$("#four_flash .flashBg ul.mobile").stop().animate({left:-_index5*326},1000);
});

$("#four_flash .but_left img").click(function(){
	if(_index5==0){
		$("ul.mobile").prepend($("ul.mobile").html());
		$("ul.mobile").css("left","-1380px");
		_index5=6
	}
	_index5--;
	$("#four_flash .flashBg ul.mobile").stop().animate({left:-_index5*326},1000);
});
$("#parachuteButton").click(function() {

});
</script>
    <script src="http://www.jq22.com/jquery/2.1.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{% static "main/js/jquery-2.1.1.min.js" %}"><\/script>')</script>
	<script>
	(function ($) {
	    var cards = $('.card-drop'), toggler = cards.find('.toggle'), links = cards.find('ul>li>a'), li = links.parent('li'), count = links.length, width = 100;
	    li.each(function (i) {
	        $(this).css('z-index', count - i);
	    });
	    function setClosed() {
	        li.each(function (index) {
	            $(this).css('top', index * 4).css('width', width - index * 0.5 + '%').css('margin-left', index * 0.25 + '%');
	        });
	        li.addClass('closed');
	        toggler.removeClass('active');
	    }
	    setClosed();
	    toggler.on('mousedown', function () {
	        var $this = $(this);
	        if ($this.is('.active')) {
	            setClosed();
	        } else {
	            $this.addClass('active');
	            li.removeClass('closed');
	            li.each(function (index) {
	                $(this).css('top', 60 * (index + 1)).css('width', '100%').css('margin-left', '0px');
	            });
	        }
	    });
	    links.on('click', function (e) {
	        var $this = $(this), label = $this.data('label');
	        icon = $this.children('i').attr('class');
	        li.removeClass('active');
	        if ($this.parent('li').is('active')) {
	            $this.parent('li').removeClass('active');
	        } else {
	            $this.parent('li').addClass('active');
	        }
	        toggler.children('span').text(label);
	        toggler.children('i').removeClass().addClass(icon);
	        setClosed();
	        e.preventDefault;
	    });
	}(jQuery));
	</script>
{% endblock %}